### ISSUE TITLE
Share button is not centred

### ISSUE THREAD

**Issue by MagicLike** [LinkStackOrg/stargazer#1]
![grafik](https://user-images.githubusercontent.com/82117109/189958551-37d08c5a-2954-4e74-a8f9-5d975ab2ef59.png)

**Comment by JulianPrieber** [comment]
Oh noh

**Comment by JulianPrieber** [comment]
Waaaiiit.

Could you hold down Ctrl and press F5 on your LittleLink page for me?

**Comment by MagicLike** [comment]
I did, but nothing changes...

**Comment by JulianPrieber** [comment]
Hmm, that's weird. This should just be a caching issue. This icon shouldn't even be used anymore.

**Comment by JulianPrieber** [comment]
Ohhh wait. It really does look like that on Firefox.

**Comment by JulianPrieber** [comment]
I must have overwritten this commit... https://github.com/JulianPrieber/littlelink-custom/commit/d28cef5193693d23444429ad1bc3853d466d032b

**Comment by JulianPrieber** [comment]
https://github.com/JulianPrieber/littlelink-custom/commit/1c6f9d17466a86075f0e9914b20f23d603698047

**Comment by MagicLike** [comment]
Thanks!
(And sorry for not responding)

**Comment by MagicLike** [comment]
It also works now as expected!
